// Package forge implements VORTEX Forge (build plan M13): the autonomous app
// builder. A user request ("build me an Android app for cricket scores") is
// parsed into a structured build intent, dependencies are installed, code is
// generated by the AI gateway, the app is built and QA-gated, and the artifact
// is delivered back to the requesting chat. All orchestration is stdlib-only;
// the AI provider is reached through the agents.AIGateway interface.
//
// This file parses a free-form user message into a structured BuildIntent.
package forge

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/vortex-run/vortex/internal/agents"
)

// AppType classifies what kind of artifact a build produces.
type AppType string

// App types.
const (
	AppTypeWeb          AppType = "web"
	AppTypeMobile       AppType = "mobile"
	AppTypeAPI          AppType = "api"
	AppTypeScript       AppType = "script"
	AppTypeDataPipeline AppType = "data_pipeline"
	AppTypeBot          AppType = "bot"
)

// StackChoice records the chosen technology stack for a build.
type StackChoice struct {
	Backend  string `json:"backend"`  // "fastapi"|"express"|"go"|"none"
	Frontend string `json:"frontend"` // "flutter"|"react"|"none"
	ML       string `json:"ml"`       // "sklearn"|"pytorch"|"none"
	Database string `json:"database"` // "sqlite"|"postgres"|"none"
}

// BuildIntent is the structured interpretation of a user request.
type BuildIntent struct {
	AppType         AppType     `json:"app_type"`
	Description     string      `json:"description"`
	Requirements    []string    `json:"requirements"`
	DeliveryTargets []string    `json:"delivery_targets"` // "apk"|"web"|"api"|"script"
	Stack           StackChoice `json:"stack"`
	NeedsLiveData   bool        `json:"needs_live_data"`
	ClarifyingQs    []string    `json:"clarifying_questions"`
}

// IntentParser turns a user message into a BuildIntent.
type IntentParser interface {
	Parse(ctx context.Context, userMsg string) (BuildIntent, error)
}

// --- AIIntentParser ---------------------------------------------------------

const intentSystemPrompt = `You are VORTEX Forge's intent parser. Given a user's app-build request, respond with ONLY a JSON object of the form:
{"app_type":"web|mobile|api|script|data_pipeline|bot","description":"...","requirements":[...],"delivery_targets":["apk"|"web"|"api"|"script"],"stack":{"backend":"fastapi|express|go|none","frontend":"flutter|react|none","ml":"sklearn|pytorch|none","database":"sqlite|postgres|none"},"needs_live_data":bool,"clarifying_questions":[...]}
Return only the JSON, no prose.`

// AIIntentParser parses intent using the AI gateway.
type AIIntentParser struct {
	gateway agents.AIGateway
}

// NewAIIntentParser builds an AI-backed parser.
func NewAIIntentParser(gateway agents.AIGateway) *AIIntentParser {
	return &AIIntentParser{gateway: gateway}
}

// Parse asks the AI gateway to classify the request into a BuildIntent. The
// caller's context is intentionally not used for the provider call (see below).
func (p *AIIntentParser) Parse(_ context.Context, userMsg string) (BuildIntent, error) {
	if strings.TrimSpace(userMsg) == "" {
		return BuildIntent{}, fmt.Errorf("forge: empty user message")
	}
	// Intent parsing calls a (possibly slow) provider; decouple from the
	// caller's context with a 60s floor so a short-lived TUI request can't
	// cancel the parse mid-flight.
	parseCtx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	reply, err := p.gateway.Complete(parseCtx, userMsg, intentSystemPrompt)
	if err != nil {
		return BuildIntent{}, fmt.Errorf("forge: intent completion: %w", err)
	}
	var intent BuildIntent
	if err := json.Unmarshal([]byte(extractJSON(reply)), &intent); err != nil {
		return BuildIntent{}, fmt.Errorf("forge: parsing intent JSON: %w", err)
	}
	if intent.Description == "" {
		intent.Description = userMsg
	}
	return intent, nil
}

// languageKeywords maps a requested language to the words that imply it.
var languageKeywords = map[string][]string{
	"c++":  {"c++", "cpp", " cplus plus"},
	"c":    {" in c", "c program", "c language"},
	"rust": {"rust"},
	"java": {"java "},
}

// RequestedLanguage returns the explicit compiled language the user asked for
// (c, c++, rust, java), or "" when none is detected. It only matches languages
// that need a toolchain check; interpreted languages are not returned.
func RequestedLanguage(userMsg string) string {
	msg := " " + strings.ToLower(userMsg) + " "
	for lang, kws := range languageKeywords {
		for _, kw := range kws {
			if strings.Contains(msg, kw) {
				return lang
			}
		}
	}
	return ""
}

// CompilerGate checks whether the language explicitly requested in userMsg has
// an available toolchain. When a compiled language is requested but its compiler
// is missing, it returns a user-facing message suggesting installed
// alternatives and ok=false (the orchestrator should NOT start a build). When
// no specific language is requested, or its compiler is present, ok=true.
func CompilerGate(userMsg string) (msg string, ok bool) {
	lang := RequestedLanguage(userMsg)
	if lang == "" {
		return "", true
	}
	found, _, hint := CheckCompiler(lang)
	if found {
		return "", true
	}
	spec := compilerSpecs[lang]
	var b strings.Builder
	fmt.Fprintf(&b, "%s compiler not found on this machine.\n", spec.Language)
	b.WriteString("I can write the same program in:\n")
	for _, alt := range availableLanguages() {
		b.WriteString("  • " + alt + " (installed ✓)\n")
	}
	fmt.Fprintf(&b, "Or install %s: %s\n", spec.Language, hint)
	b.WriteString("Which would you prefer?")
	return b.String(), false
}

// extractJSON returns the first {...} object found in s (models sometimes wrap
// JSON in prose or code fences).
func extractJSON(s string) string {
	start := strings.IndexByte(s, '{')
	end := strings.LastIndexByte(s, '}')
	if start >= 0 && end > start {
		return s[start : end+1]
	}
	return s
}

// --- RuleIntentParser -------------------------------------------------------

// RuleIntentParser is a keyword-based fallback used when no AI gateway is
// available. It is deterministic and needs no network.
type RuleIntentParser struct{}

// NewRuleIntentParser builds the rule-based parser.
func NewRuleIntentParser() *RuleIntentParser { return &RuleIntentParser{} }

// Parse classifies the message by keyword heuristics.
func (RuleIntentParser) Parse(_ context.Context, userMsg string) (BuildIntent, error) {
	msg := strings.ToLower(strings.TrimSpace(userMsg))
	if msg == "" {
		return BuildIntent{}, fmt.Errorf("forge: empty user message")
	}

	intent := BuildIntent{Description: userMsg}

	switch {
	case containsAny(msg, "apk", "android", "mobile app", "flutter"):
		intent.AppType = AppTypeMobile
		intent.DeliveryTargets = []string{"apk"}
		intent.Stack = StackChoice{Frontend: "flutter", Backend: "none", ML: "none", Database: "none"}
	case containsAny(msg, "rest api", "api endpoint", "backend api", "create a rest", "an api"):
		intent.AppType = AppTypeAPI
		intent.DeliveryTargets = []string{"api"}
		intent.Stack = StackChoice{Backend: "go", Frontend: "none", ML: "none", Database: "none"}
	case containsAny(msg, "data pipeline", "etl", "pipeline"):
		intent.AppType = AppTypeDataPipeline
		intent.DeliveryTargets = []string{"script"}
		intent.Stack = StackChoice{Backend: "none", Frontend: "none", ML: "none", Database: "none"}
	case containsAny(msg, "bot", "telegram bot", "discord bot"):
		intent.AppType = AppTypeBot
		intent.DeliveryTargets = []string{"script"}
		intent.Stack = StackChoice{Backend: "go", Frontend: "none", ML: "none", Database: "none"}
	case containsAny(msg, "script", "program", "cli"):
		intent.AppType = AppTypeScript
		intent.DeliveryTargets = []string{"script"}
		intent.Stack = StackChoice{Backend: "go", Frontend: "none", ML: "none", Database: "none"}
	case containsAny(msg, "web app", "website", "web application", "webapp", "web"):
		intent.AppType = AppTypeWeb
		intent.DeliveryTargets = []string{"web"}
		intent.Stack = StackChoice{Frontend: "react", Backend: "go", ML: "none", Database: "none"}
	default:
		intent.AppType = AppTypeWeb
		intent.DeliveryTargets = []string{"web"}
		intent.Stack = StackChoice{Frontend: "react", Backend: "go", ML: "none", Database: "none"}
		intent.ClarifyingQs = []string{"What kind of app would you like — web, mobile (APK), API, or script?"}
	}

	if containsAny(msg, "live data", "real-time", "realtime", "fetch", "api data") {
		intent.NeedsLiveData = true
	}
	return intent, nil
}

// containsAny reports whether s contains any of the substrings.
func containsAny(s string, subs ...string) bool {
	for _, sub := range subs {
		if strings.Contains(s, sub) {
			return true
		}
	}
	return false
}
